defaults:
  - default

path: stabilityai/stablelm-2-1_6b-chat
type: CausalLM
path_to_load_script: ../../examples/configs/model/default_causal.py

load_model_args:
  device_map: cpu
load_tokenizer_args: {}
