defaults:
  - polygraph_eval_triviaqa_default_instruct
  - model: bloomz-560m
  - _self_

topk: 5
description: "Provide your ${topk} best guesses and the probability that each is correct (0.0 to 1.0) for the following question. Give ONLY the guesses and probabilities, no other words or explanation. For example:\n\nG1: <first most likely guess, as short as possible; not a complete sentence, just the guess!>\nP1: <the probability between 0.0 and 1.0 that G1 is correct, without any extra commentary whatsoever; just the probability!>\n...\nG${topk}: <${topk}-th most likely guess, as short as possible; not a complete sentence, just the guess!>\nP${topk}: <the probability between 0.0 and 1.0 that G${topk} is correct, without any extra commentary whatsoever; just the probability!>"
few_shot_prompt: "Question: {question}\nG1: {answer}\nP1: <number between 0.0 and 1.0 reflecting confidence in this guess>\n...\nG${topk}: <other guess>\nP${topk}: <probability of this guess>"
prompt: "Question: {question}\n"
max_new_tokens: 30
n_shot: 5
output_ignore_regex: "(?s).*G1: |\nP1.*"

use_density_based_ue: false
use_seq_ue: false
use_tok_ue: false
use_ens_ue: false
use_verb_ue: false
generation_metrics: null
ens_type: 

additional_estimators: 
  - module: lm_polygraph.estimators.verbalized_1s
    class_name: Verbalized1S
    kwargs:
      confidence_regex: 'P1: (\d+\.\d+)'
