# This workflow will trigger Read the Docs to build your documentation when you push to the main branch

name: Read the Docs

on:
  push:
    branches:
      - rtd_redux

permissions:
  contents: read

jobs:
  build:
    - name: Trigger RTDs build
      uses: dfm/rtds-action@v1
      with:
        webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
        webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
        commit_ref: ${{ github.ref }}
